Add `sbt-version-policy` for checking compatability
sbt 1.5 and above can detect whether two dependencies with different
versions are compatible (ie the newer version can safely evict the
other), so long as the libraries:

* declare their versioning scheme, eg like this:
  ```
  ThisBuild / versionScheme := Some("early-semver")
  ```
* respect their versioning scheme, and bump the right part of the
  version number based on how incompatible the new release is!
  eg for `early-semver`, with a current version number of
  `major.minor.patch`, bump:
  * `patch` : totally compatible
  * `minor` : backward Source compatability is broken
    (upgrading a consuming project to use the new version, without
    altering the consuming code, could cause compile errors or
    unintended behavioral changes)
  * `major` : backward Binary compatability is broken
    (a consuming project that even transitively pulls in the new
    version could get linkage errors, eg `NoSuchMethodError`)

https://www.scala-lang.org/blog/2021/02/16/preventing-version-conflicts-with-versionscheme.html
https://github.com/scalacenter/sbt-version-policy
https://docs.scala-lang.org/overviews/core/binary-compatibility-for-library-authors.html